[project]
name = "qualibration-libs"
version = "0.2.1"
description = "Utility library supporting calibration nodes and graphs for the QUAlibration graphs platform."
readme = "README.md"
authors = [{ name = "Theo Laudat", email = "theo@quantum-machines.co" }]
requires-python = ">=3.10, <3.13"
dependencies = [
    "colorama>=0.4.6",
    "lmfit>=1.3.3",
    "matplotlib>=3.10.7",
    "numpy>=1.20.0",
    "qm-qua>=1.2.2",
    "quam_builder>=0.1.2",
    "qualibrate>=0.2.1",
    "scipy>=1.13.1",
    "xarray>=2024.7.0",
]

[project.scripts]
setup-qualibrate-config = "qualibration_libs.config.setup_qualibrate:setup_qualibrate_config"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
packages = ["qualibration_libs"]

[[tool.poetry.source]]
name = "qm-pypi"
url = "https://quantum-machines-439440158105.d.codeartifact.us-east-1.amazonaws.com/pypi/qm-pypi/simple/"
priority = "supplemental"

